services:
  backend:
    build: ./api-planify
    ports:
      - "3000:3000"
    networks:
      - app-network

  frontend:
    build: ./app-planify
    ports:
      - "4200:4200"
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
