services:
  db:
    image: mysql:8
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db_planify
    ports:
      - "3306:3306"
    networks:
      - app-network
    volumes:
      - mysql-data:/var/lib/mysql

  backend:
    stdin_open: true
    tty: true
    build: ./api-planify
    ports:
      - "3000:3000"
    depends_on:
      - db
    networks:
      - app-network
    volumes:
      - ./api-planify:/app
    command:
      - bash
      - -c
      - |
        npm install
        dockerize -wait tcp://db:3306 -timeout 60s
        npm start

  frontend:
    stdin_open: true
    tty: true
    build: ./app-planify
    ports:
      - "4200:4200"
    depends_on:
      - backend
    networks:
      - app-network
    volumes:
      - ./app-planify:/app
    command:
      - bash
      - -c
      - |
        npm install
        npm start
    environment:
      - NG_CLI_ANALYTICS=false


networks:
  app-network:
    driver: bridge

volumes:
  mysql-data: {}
